### ISSUE TITLE
RuntimeException: Unable to start service org.akvo.flow.service.FileChangeTrackingService@c9cb87e with null: java.l...

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1021]
https://sentry.io/akvo-foundation/flow-android/issues/409510938/

```
NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
    at com.google.android.gms.gcm.GcmTaskService.onStartCommand
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3394)
    at android.app.ActivityThread.-wrap21(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
    at android.os.Handler.dispatchMessage(Handler.java:110)
...
(5 additional frame(s) were not displayed)

RuntimeException: Unable to start service org.akvo.flow.service.FileChangeTrackingService@c9cb87e with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3411)
    at android.app.ActivityThread.-wrap21(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:203)
...
(4 additional frame(s) were not displayed)

Unable to start service org.akvo.flow.service.FileChangeTrackingService@c9cb87e with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
```

**Comment by valllllll2000** [comment]
related to issue + fix https://github.com/google/gcm/issues/87

**Comment by valllllll2000** [comment]
## Test plan
Nothing to test manually

**Comment by janagombitova** [comment]
Ah, lucky me :)
