### ISSUE TITLE
When Caddislfy result is empty or a String the app crashes with JsonSyntaxException

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1024]
https://sentry.io/akvo-foundation/flow-android/issues/473617889/

```
IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
    at com.google.gson.Gson.fromJson(Gson.java:888)
    at com.google.gson.Gson.fromJson(Gson.java:853)
    at com.google.gson.Gson.fromJson(Gson.java:802)
...
(26 additional frame(s) were not displayed)

JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at org.akvo.flow.ui.model.caddisfly.CaddisflyJsonMapper.transform(CaddisflyJsonMapper.java:41)
    at org.akvo.flow.ui.view.CaddisflyQuestionView.rehydrate(CaddisflyQuestionView.java:98)
    at org.akvo.flow.ui.view.QuestionGroupTab.displayResponses(QuestionGroupTab.java:209)
    at org.akvo.flow.ui.view.QuestionGroupTab.loadState(QuestionGroupTab.java:187)
    at org.akvo.flow.ui.adapter.SurveyTabAdapter.loadTab(SurveyTabAdapter.java:88)
...
(25 additional frame(s) were not displayed)

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
```

**Comment by janagombitova** [comment]
Tested the apk and problem is solved 👍

**Comment by janagombitova** [comment]
Yep, still works well 👍
