### ISSUE TITLE
Caddisfly images issue

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1129]
Sentry caught this exception:
java.io.FileNotFoundException: /storage/emulated/0/akvoflow/data/media/result-images: open failed: EISDIR (Is a directory)java.io
	at libcore.io.IoBridge.open(IoBridge.java:452)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at org.akvo.flow.data.datasource.FileHelper.copyFile(FileHelper.java:57)
	at org.akvo.flow.data.datasource.FileHelper.copyFileToFolder(FileHelper.java:44)
	at org.akvo.flow.data.datasource.FileDataSource.copyFiles(FileDataSource.java:100)
	at org.akvo.flow.data.datasource.FileDataSource.moveFiles(FileDataSource.java:85)
	at org.akvo.flow.data.datasource.FileDataSource.moveMediaFiles(FileDataSource.java:60)
	at org.akvo.flow.data.repository.FileDataRepository.moveFiles(FileDataRepository.java:63)
	at org.akvo.flow.domain.interactor.MakeDataPrivate.buildUseCaseObservable(MakeDataPrivate.java:59)
	at org.akvo.flow.domain.interactor.MakeDataPrivate.execute(MakeDataPrivate.java:49)
	at org.akvo.flow.service.DataSyncService.onHandleIntent(DataSyncService.java:1...
Caddisfly images seem to be inside media/result-images folder so they are not moved to the private folder properly.

**Comment by valllllll2000** [comment]
Update: still investigating to check if the folder is useful or not before either deeting it or adding logic to move it aswell

**Comment by valllllll2000** [comment]
After talking to Nishal, it seems the folder must have been copied entierely as passed as extra by the app. We need to improve the way we copy Caddisfly images avoiding the src.renameTo(dst) but actually copying files one by one.

**Comment by valllllll2000** [comment]
## Test plan
on device inside akvoflow/data create media folder if does not exist. inside media create a folder called result-images and put some random images there.
Launch the app, after a few seconds check that folder:
Images should be gone
result-images should be gone
media folder should be gone.

**Comment by valllllll2000** [comment]
works as expected
