### ISSUE TITLE
TimeCheckActivity crashes

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1229]
https://sentry.io/akvo-foundation/flow-android/issues/249476689/

```
IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    at org.akvo.flow.activity.TimeCheckActivity.onCreate(TimeCheckActivity.java:45)
...
(13 additional frame(s) were not displayed)

RuntimeException: Unable to start activity ComponentInfo{org.akvo.flow/org.akvo.flow.activity.TimeCheckActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
    at android.app.ActivityThread.access$1000(ActivityThread.java:218)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
    at android.os.Handler.dispatchMessage(Handler.java:102)
...
(6 additional frame(s) were not displayed)

Unable to start activity ComponentInfo{org.akvo.flow/org.akvo.flow.activity.TimeCheckActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```

**Comment by valllllll2000** [comment]
## Test plan
Try misconfiguring time of your device and restart the app, you should see a dialog showing that you need to adjust your time and no crash.

**Comment by kymni** [comment]
Confirmed app no longer crashes when time is misconfigured
