### ISSUE TITLE
Crash due to null SurveyGroup

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1274]
https://sentry.io/akvo-foundation/flow-android/issues/685668844/?referrer=github_plugin

```
NullPointerException: Attempt to invoke virtual method 'java.lang.String org.akvo.flow.domain.SurveyGroup.getRegisterSurveyId()' on a null object reference
    at org.akvo.flow.data.database.SurveyDbDataSource.getRegistrationForm(SurveyDbDataSource.java:329)
    at org.akvo.flow.activity.SurveyActivity.displayForm(SurveyActivity.java:468)
    at org.akvo.flow.activity.SurveyActivity.access$300(SurveyActivity.java:88)
    at org.akvo.flow.activity.SurveyActivity$3.onNext(SurveyActivity.java:451)
    at org.akvo.flow.activity.SurveyActivity$3.onNext(SurveyActivity.java:436)
...
(10 additional frame(s) were not displayed)

IllegalStateException: Fatal Exception thrown on Scheduler.
    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:7406)
...
(3 additional frame(s) were not displayed)

Fatal Exception thrown on Scheduler.
```

**Comment by valllllll2000** [comment]
closing as no longer found on sentry
