### ISSUE TITLE
Caddisfly images can be a folder

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1293]
Here is the crash found by sentry:

```
FileNotFoundException: /storage/emulated/0/Akvo Caddisfly/result-images (Is a directory)
    at org.akvo.flow.data.util.FileHelper.copyFile(FileHelper.java:107)

java.io.FileNotFoundException: /storage/emulated/0/Akvo Caddisfly/result-images (Is a directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.akvo.flow.data.util.FileHelper.copyFile(FileHelper.java:107)
	at org.akvo.flow.data.datasource.FileDataSource.copyFile(FileDataSource.java:74)
	at org.akvo.flow.data.repository.FileDataRepository.copyFile(FileDataRepository.java:119)
	at org.akvo.flow.domain.interactor.CopyFile.buildUseCaseObservable(CopyFile.java:57)
	at org.akvo.flow.domain.interactor.UseCase.execute(UseCase.java:61)
	at org.akvo.flow.presentation.form.caddisfly.CaddisflyPresenter.onImageReady(CaddisflyPresenter.java:62)
	at org.akvo.flow.ui.view.CaddisflyQuestionView.questionComplete(CaddisflyQuestionView.java:149)
	at org.akvo.flow.ui.view.QuestionGroupTab.onQuestionComplete(QuestionGroupTab.java:143)
	at org.akvo.flow.ui.adapter.SurveyTabAdapter.onQuestionComplete(SurveyTabAdapter.java:140)
	at org.ak...
```

This is due to the fact that sometimes Caddisfly passed the whole folder instead of the image. 
We should ignore the folder.

**Comment by valllllll2000** [comment]
## Test plan
Try several caddisfly tests (especially ones that require images).
