### ISSUE TITLE
FormInstance mappers error

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1313]
Sentry reported the following error when mapping form instances
```
java.lang.NullPointerException
	at org.akvo.flow.data.entity.FormInstanceMetadataMapper.transform(FormInstanceMetadataMapper.java:53)
	at org.akvo.flow.data.repository.SurveyDataRepository$26.apply(SurveyDataRepository.java:493)
	at org.akvo.flow.data.repository.SurveyDataRepository$26.apply(SurveyDataRepository.java:490)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.poll(ObservableMap.java:76)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.drain(ObservableConcatMap.java:193)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onSubscribe(ObservableConcatMap.java:103)
	at io.reactivex.internal.observers.BasicFuseableObserver.onSubscribe(BasicFuseableObserver.java:66)
	at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subsc...
```
This happens because the FormInstance is not found in the database (not sure why, maybe a threading issue)
## Solution
Add check for null values and create tests for these mappers

**Comment by valllllll2000** [comment]
## Test plan
Regression tests should catch any issue (syncing of data)
