### ISSUE TITLE
Camera seems to be not found on some device

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1350]
Error log found by sentry:

```
Exception: No camera on device or no app found to take pictures
    at org.akvo.flow.ui.Navigator.navigateToTakePhoto(Navigator.java:128)
    at org.akvo.flow.activity.FormActivity.takePhoto(FormActivity.java:886)
    at org.akvo.flow.activity.FormActivity.onQuestionInteraction(FormActivity.java:776)
    at org.akvo.flow.ui.view.QuestionView.notifyQuestionListeners(QuestionView.java:288)
    at org.akvo.flow.ui.view.QuestionView.notifyQuestionListeners(QuestionView.java:294)
```

Seems to mean on some old samsung devices 
``` packageManager.hasSystemFeature(PackageManager.FEATURE_CAMERA_ANY)```
returns false even if the camera is available

**Comment by valllllll2000** [comment]
## Test plan
On your device Settings -> Apps  find the camera app and disable it
Now try answering photo question, it should not work (nothing happens) but no crash
