### ISSUE TITLE
Error downloading apk updates

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1355]
Crash found by sentry:

```
FileUriExposedException: file:///storage/emulated/0/Android/data/org.akvo.flow/files/apk/2.7.2/flow-2.7.2.apk exposed beyond app through Intent.getData()
    at org.akvo.flow.ui.Navigator.installAppUpdate(Navigator.java:337)
    at org.akvo.flow.activity.AppUpdateActivity.onDownloadSuccess(AppUpdateActivity.java:325)
    at org.akvo.flow.activity.AppUpdateActivity.access$800(AppUpdateActivity.java:59)
    at org.akvo.flow.activity.AppUpdateActivity$UpdateAsyncTask.onPostExecute(AppUpdateActivity.java:228)
    at org.akvo.flow.activity.AppUpdateActivity$UpdateAsyncTask.onPostExecute(AppUpdateActivity.java:164)
...
(21 additional frame(s) were not displayed)

file:///storage/emulated/0/Android/data/org.akvo.flow/files/apk/2.7.2/flow-2.7.2.apk exposed beyond app through Intent.getData()
```

Due to the way the uri is being used and the new permissions

**Comment by valllllll2000** [comment]
This bug was introduced in version 2.7.1 and is due to the new way android handles file permissions on devices with android 7.0 ++. After the fix is deployed, the devices with Android 7.0-9.0 that have updated to 2.7.1 will not be able to update the traditional way. We need to instruct them to update entering their browser and typing https://instance.akvoflow.org/app2 and follow the instructions to download the apk which will update their app. You may see the following message:
"For you security, your phone is not allowed to install unknown apps from this source."
Press "settings"
Check "Allow from this source"
Press back and press "install" again.
This time the app update will install correctly.
