### ISSUE TITLE
IllegalStateException in FormActivity

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#552]
Here is the stacktrace:

```
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: 
	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
	at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1494)
	at org.akvo.flow.dao.SurveyDbAdapter.deleteResponse(SurveyDbAdapter.java:951)
	at org.akvo.flow.activity.FormActivity.deleteResponse(FormActivity.java:562)
	at org.akvo.flow.activity.FormActivity.onQuestionInteraction(FormActivity.java:646)
	at org.akvo.flow.ui.view.QuestionView.notifyQuestionListeners(QuestionView.java:335)
	at org.akvo.flow.ui.view.QuestionView.notifyQuestionListeners(QuestionView.java:341)
	at org.akvo.flow.ui.view.QuestionView.setResponse(QuestionView.java:519)
	at org.akvo.flow.ui.view.QuestionView.resetQuestion(QuestionView.java:357)
	at org.akvo.flow.ui.view.GeoQuestionView.resetQuestion(GeoQuestionView.java:139)
	at org.akvo.flow.ui.view.GeoQuestionView.onTimeout(GeoQuestionView.java:194)
	at org.akvo.flow.event.TimedLocationListener$1$1.run(TimedLocationListener.java:83)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5257)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method):
```
TODO: find a way to reproduce it
Happens to latest version of the app the 2.2.9
When filling the form...

**Comment by valllllll2000** [comment]
detected by sentry also:
https://sentry.io/akvo-foundation/flow-android/issues/228476777/

**Comment by valllllll2000** [comment]
Here is a related issue from sentry
https://sentry.io/akvo-foundation/flow-android/issues/229783219/

**Comment by valllllll2000** [comment]
related issue found by sentry
https://sentry.io/akvo-foundation/flow-android/issues/229824405/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/236429116/

**Comment by valllllll2000** [comment]
this has been fixed in https://github.com/akvo/akvo-flow-mobile/issues/675 and no longer happens since release 2.3.1

**Comment by valllllll2000** [comment]
Unfortunately, the issue is still happening in version 2.3.4 https://sentry.io/akvo-foundation/flow-android/issues/250418178/events/5784172840/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/250418178/

**Comment by valllllll2000** [comment]
## Test plan
I did not manage to reproduce it so do not know how to test it. Just make sure when trying to add a datapoint, the form is displayed correctly.

**Comment by janagombitova** [comment]
everything worked for me, so let's hope you tackled this mystery
