### ISSUE TITLE
Crash: NullPointerException when trying to open FormActivity

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#637]
https://sentry.io/akvo-foundation/flow-android/issues/227573007/

```
RuntimeException: Unable to start activity ComponentInfo{org.akvo.flow/org.akvo.flow.activity.FormActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.akvo.flow.domain.Survey.getName()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
    at android.app.ActivityThread.access$800(ActivityThread.java:178)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
    at android.os.Handler.dispatchMessage(Handler.java:111)
...
(6 additional frame(s) were not displayed)

NullPointerException: Attempt to invoke virtual method 'java.lang.String org.akvo.flow.domain.Survey.getName()' on a null object reference
    at org.akvo.flow.activity.FormActivity.onCreate(FormActivity.java:132)
...
(9 additional frame(s) were not displayed)

Unable to start activity ComponentInfo{org.akvo.flow/org.akvo.flow.activity.FormActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.akvo.flow.domain.Survey.getName()' on a null object reference
```

**Comment by valllllll2000** [comment]
This issue may be linked
https://sentry.io/akvo-foundation/flow-android/issues/227572998/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/249476689/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/252670973/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/239313574/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/248830223/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/240758883/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/247372206/

**Comment by valllllll2000** [comment]
## Test plan
In order to reproduce this error, one way to do it is to delete all forms stored in your device, here is how:
1) Install the app, log in and make sure you get all your assigned forms.
2) You will need some file browsing app I use File Commander or Astro but there are many more
3) With the fie browser go to sdcard (or internal memory) /Android/Data/org.akvo.flow/files/forms
4) Delete all the forms in there (all the .xml files)
Now try to create a new datapoint by pressing the "+" in the menu. You should see the error message and the app will not crash (at this point with the older versions the app would crash). There may be other reasons why the form got deleted but I have found this is the easiest way to reproduce it.
