### ISSUE TITLE
Crash in RecordActivity

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#655]
https://sentry.io/akvo-foundation/flow-android/issues/236322743/

```
RuntimeException: Unable to resume activity {org.akvo.flow/org.akvo.flow.activity.RecordActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.akvo.flow.domain.SurveyedLocale.getDisplayName(android.content.Context)' on a null object reference
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4221)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4323)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426)
    at android.app.ActivityThread.access$1100(ActivityThread.java:229)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
...
(6 additional frame(s) were not displayed)

NullPointerException: Attempt to invoke virtual method 'java.lang.String org.akvo.flow.domain.SurveyedLocale.getDisplayName(android.content.Context)' on a null object reference
    at org.akvo.flow.activity.RecordActivity.displayRecord(RecordActivity.java:135)
    at org.akvo.flow.activity.RecordActivity.onResume(RecordActivity.java:118)
...
(10 additional frame(s) were not displayed)

Unable to resume activity {org.akvo.flow/org.akvo.flow.activity.RecordActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.akvo.flow.domain.SurveyedLocale.getDisplayName(android.content.Context)' on a null object reference
```

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/236879453/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/249629409/

**Comment by valllllll2000** [comment]
## Test plan
Try opening existing datapoints on device:
-> if they are in "saved" state you should be able to edit
-> if they are already exported or synced you can only view
Creating new datapoint:
When the survey is not monitored you should see the form directly
If survey is monitored you should first see RecordActivity which is the screen with 2 tabs: Forms and History (history should be empty since you have not created a new datapoint yet)

**Comment by janagombitova** [comment]
All as expected 👍
