### ISSUE TITLE
Crash when loading geoquestion: NumberFormatException: Invalid double: "3,6"

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#697]
https://sentry.io/akvo-foundation/flow-android/issues/246391529/

```
NumberFormatException: Invalid double: "3,6"
    at org.akvo.flow.ui.view.GeoQuestionView.rehydrate(GeoQuestionView.java:179)
    at org.akvo.flow.ui.view.QuestionGroupTab.displayResponses(QuestionGroupTab.java:188)
    at org.akvo.flow.ui.view.QuestionGroupTab.loadState(QuestionGroupTab.java:179)
    at org.akvo.flow.ui.adapter.SurveyTabAdapter.loadTab(SurveyTabAdapter.java:105)
    at org.akvo.flow.ui.adapter.SurveyTabAdapter.instantiateItem(SurveyTabAdapter.java:193)
...
(19 additional frame(s) were not displayed)

Invalid double: "3,6"
```

**Comment by valllllll2000** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvo-problems-with-version-2-dot-3-1-on-smart-phone
Assignee: Lissy van Noort

Message:
Hi Akvo team,

 

I am Minh from Vietnam Biogas Project Management Unit. Our dashboard is
&lt;https://biogas-programme.akvoflow.org/admin&gt;
https://biogas-programme.akvoflow.org/admin

 

We found some problems in Akvo apps on smart phone with new version 2.3.1. I
elaborate our issue in the attached file.

**Comment by valllllll2000** [comment]
## Test plan: 
The crash was happening to some surveys which have a location question and the altitude has a string in it, example: 3,6 or 231,2 not sure if you can create a datapoint in such a way that is similar to the data from the dashboard owners experiencing this issue.

**Comment by janagombitova** [comment]
👍  we both confirmed the fix works
