### ISSUE TITLE
NumberFormatException: Invalid long: "21474836472147483647"

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#701]
https://sentry.io/akvo-foundation/flow-android/issues/253861182/

```
NumberFormatException: Invalid long: "21474836472147483647"
    at org.akvo.flow.ui.view.GeoQuestionView.generateCode(GeoQuestionView.java:160)
    at org.akvo.flow.ui.view.GeoQuestionView.updateCode(GeoQuestionView.java:219)
    at org.akvo.flow.ui.view.GeoQuestionView.onFocusChange(GeoQuestionView.java:257)
...
(79 additional frame(s) were not displayed)

Location response code cannot be generated: Invalid long: "21474836472147483647"
java.lang.NumberFormatException: Invalid long: "21474836472147483647"
	at java.lang.Long.invalidLong(Long.java:124)
	at java.lang.Long.parse(Long.java:366)
	at java.lang.Long.parseLong(Long.java:353)
	at java.lang.Long.parseLong(Long.java:321)
	at org.akvo.flow.ui.view.GeoQuestionView.generateCode(GeoQuestionView.java:160)
	at org.akvo.flow.ui.view.GeoQuestionView.updateCode(GeoQuestionView.java:219)
	at org.akvo.flow.ui.view.GeoQuestionView.onFocusChange(GeoQuestionView.java:257)
	at android.view.View.onFocusChanged(View.java:5206)
	at android.widget.TextView.onFocusChanged(TextView.java:7913)
	at android.view.View.clearFocusInternal(View.java:5089)
	at android.view.View.unFocus(View.java:5122)
	at android.view.ViewGroup.unFocus(ViewGroup.java:857)
	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:658)
	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:664)
	at android.view.View.handleFocusGainInternal(View.java:4955)
	at android.view.View.requestFocusNoSearch(View.java:7678)
	at android.view.View.requestFocus(View.java:7657)
	at android.view.View.requestFocus(View.java:7624)
	at android.view.View.requestFocus(View.java:7603)
	at android.view.View.onTouchEvent(View.java:9439)
	at android.widget.TextView.onTouchEvent(TextView.java:7965)
	at android.view.View.dispatchTouchEvent(View.java:8471)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
	at android.view.View.dispatchPointerEvent(View.java:8666)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```

**Comment by valllllll2000** [comment]
this is probably due to the manual input values for coordinates not being validated https://github.com/akvo/akvo-flow-mobile/issues/679

**Comment by valllllll2000** [comment]
## Test plan
You need an android device with Andriod 5.1.* preferably a samsung.
1) Create a question which requires geo locations and allows manual input
2) write some lat/lon data and for height write a big number of at least 20 numbers.
3) Make sure the app does not crash
