### ISSUE TITLE
Crash when play services and google play apps missing

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#715]
https://sentry.io/akvo-foundation/flow-android/issues/237355393/

```
ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.android.gms flg=0x80000 pkg=com.android.vending }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
    at android.app.Activity.startActivityForResult(Activity.java:3745)
    at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
...
(15 additional frame(s) were not displayed)

No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.android.gms flg=0x80000 pkg=com.android.vending }
```

**Comment by valllllll2000** [comment]
This seems to happen on devices which do not have the google play services installed (they are needed for viewing maps) and at the same time they do not have the market or google play app installed either. The crash does not occur in our code so there is nothing we can do at the moment except trying to update play services library (which has its own issues) we use in the app and hope google has fixed the issue.

**Comment by guneetnarula** [comment]
Just saw this and wanted add a comment since I have android phones without play services or play store. Flow does **not** crash at all in both Android 5.1 and 6.0.1 for me. This has been the case since an year now.

**Comment by valllllll2000** [comment]
@guneetnarula Thank you for the update, that is very interesting as this bug is hard to reproduce. I do have a few questions: 
1) If you do not have play services installed, are you able to still see the maps for example for the datapoints list, the second tab or is there a button there saying you should download play services?
2) Are you using the latest version of the Flow app?

**Comment by anand48jha** [comment]
No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.retailAnalytics }. I have playStore installed and playServices library installed in it. Still i am getting this issue. Please explain why i am getting this.
