### ISSUE TITLE
Crash in CascadeQuestionView

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#716]
https://sentry.io/akvo-foundation/flow-android/issues/248242300/

```
NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
    at org.akvo.flow.data.CascadeDB.getValues(CascadeDB.java:75)
    at org.akvo.flow.ui.view.CascadeQuestionView.updateSpinners(CascadeQuestionView.java:136)
    at org.akvo.flow.ui.view.CascadeQuestionView.onItemSelected(CascadeQuestionView.java:181)
...
(9 additional frame(s) were not displayed)

Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
```

**Comment by valllllll2000** [comment]
## Test plan
I was not able to reproduce the crash.
Create a cascade with multiple levels and add it to your survey.
Try filling cascade question, should never crash and cascade should work as expected.

**Comment by janagombitova** [comment]
No issues with cascades on my side either. I assume we are ready to roll on this one as well 👍
