### ISSUE TITLE
investigate OutOfMemoryError in clusters of datapoints map

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#726]
https://sentry.io/akvo-foundation/flow-android/issues/264174508/

```
RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:299)
    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
...
(3 additional frame(s) were not displayed)

OutOfMemoryError: None
    at com.google.maps.android.clustering.algo.NonHierarchicalDistanceBasedAlgorithm.getClusters(NonHierarchicalDistanceBasedAlgorithm.java:136)
    at com.google.maps.android.clustering.algo.PreCachingAlgorithmDecorator.getClustersInternal(PreCachingAlgorithmDecorator.java:98)
    at com.google.maps.android.clustering.algo.PreCachingAlgorithmDecorator.getClusters(PreCachingAlgorithmDecorator.java:72)
    at com.google.maps.android.clustering.ClusterManager$ClusterTask.doInBackground(ClusterManager.java:213)
    at com.google.maps.android.clustering.ClusterManager$ClusterTask.doInBackground(ClusterManager.java:208)
...
(9 additional frame(s) were not displayed)

An error occured while executing doInBackground()
```

**Comment by valllllll2000** [comment]
Ran analysis on both new and refactored code on my nexus 6 (quite powerful device)
* with 300 datapoints -> clusters work well and map displays datapoints correctly
* with 30 000 datapoints -> map displays datapoints but the app becomes slow as it seems obviously there is heavy processing going on there. App still usable, does not seem to be any memory leaks as memory goes up and then down after each device rotation.
* with 300 000 -> app becomes unusable and unresponsive, too much processing going on.
