### ISSUE TITLE
DrawerFragment adapter and data loading issue

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#732]
Some issues
* When rotating the device multiple times, it seems the DrawerFragment is querying for data too many times and also getLoaderManager() is called too soon.
`org.akvo.flow W/LoaderManager: Called doStart when already started: LoaderManager{4880427 in HostCallbacks{c57d6d4}}
                                                              java.lang.RuntimeException: here
                                                                  at android.support.v4.app.LoaderManagerImpl.doStart(LoaderManager.java:760)
                                                                  at android.support.v4.app.Fragment.onStart(Fragment.java:1398)
                                                                  at android.support.v4.app.Fragment.performStart(Fragment.java:2218)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                  at `
* SurveyActivity has a broadcast receiver which gets notified when surveys get reloaded (even if there are no new surveys). BroadcastReceiver should be moved directly to the Fragment.
* DrawerAdapter inside DrawerFragment should be made static to avoid memory leaks
* DrawerAdapter can be improved the way it is creating the resources while getting the views

**Comment by valllllll2000** [comment]
This is no longer relevant after the navigation drawer refactor #808
