### ISSUE TITLE
Crash related to option question

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#739]
https://sentry.io/akvo-foundation/flow-android/issues/247975538/

```
NullPointerException: Attempt to invoke virtual method 'int android.widget.RadioGroup.getChildCount()' on a null object reference
    at org.akvo.flow.ui.view.OptionQuestionView.notifyOptionsChanged(OptionQuestionView.java:182)
    at org.akvo.flow.ui.view.QuestionGroupTab.notifyOptionsChanged(QuestionGroupTab.java:133)
    at org.akvo.flow.ui.adapter.SurveyTabAdapter.notifyOptionsChanged(SurveyTabAdapter.java:93)
    at org.akvo.flow.activity.FormActivity.saveLanguages(FormActivity.java:459)
    at org.akvo.flow.activity.FormActivity.useSelectedLanguages(FormActivity.java:433)
...
(9 additional frame(s) were not displayed)

Attempt to invoke virtual method 'int android.widget.RadioGroup.getChildCount()' on a null object reference
```

This happens when options have multiple choice

**Comment by valllllll2000** [comment]
## Testing plan
Create a monitored survey with several option questions:
* Allow multiple options
* Single choice
* Allow other either of previous option combined
* Create option question without any actual questions (you have to make it non mandatory or else you cannot submit the survey).
Add at least one translation.
Open survey and start adding datapoint. Make sure all options work. 
Try switching languages, make sure app does not crash.
Once submitted, make sure everything syncs and can be also synced/viewed on other devices.

**Comment by janagombitova** [comment]
👍  collecting, language switching, syncing >> all worked fine without crashing
