### ISSUE TITLE
Geoquestion view: Fix crash related to SnackBar on some devices

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#743]
This will prevent the crash https://sentry.io/akvo-foundation/flow-android/issues/269458099/ when the rootview found is a scrollview: use parent CoordinatorLayout

```
java.lang.IllegalStateException: ScrollView can host only one direct child
    at android.widget.ScrollView.addView(ScrollView.java:232)
    at android.support.design.widget.BaseTransientBottomBar.showView(BaseTransientBottomBar.java:436)
    at android.support.design.widget.BaseTransientBottomBar$1.handleMessage(BaseTransientBottomBar.java:177)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5371)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/269522486/

**Comment by valllllll2000** [comment]
## Test plan
Create a geo location question
Press "check geolocation"
Wait for the timeout (on most devices it should timeout since gps does not work indoors)
Timeout will happen after 1 minute.
Make sure no crash

**Comment by janagombitova** [comment]
Waited for a minute, received our nice new error message, nothing crashed. All good 👍
