### ISSUE TITLE
Unable to delete saved answers (crash)

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#893]
Steps to reproduce:
Create a datapoint with at least one answer but do not submit
From datapoints list tap the saved datapoint and then select the history tab
Long press on the saved entry and select "Delete response"
Confirm
The app will crash.
Here is a stacktrace:
`java.lang.NullPointerException: null
    at org.akvo.flow.database.SurveyDbAdapter.deleteResponses(SurveyDbAdapter.java:390)
    at org.akvo.flow.database.SurveyDbAdapter.deleteSurveyInstance(SurveyDbAdapter.java:402)
    at org.akvo.flow.ui.fragment.ResponseListFragment.deleteSurveyInstance(ResponseListFragment.java:217)
    at org.akvo.flow.ui.fragment.ResponseListFragment.access$000(ResponseListFragment.java:68)
    at org.akvo.flow.ui.fragment.ResponseListFragment$2.onClick(ResponseListFragment.java:195)
    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5602)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/365786298/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/371115320/

**Comment by valllllll2000** [comment]
## Test plan
try deleting a saved answer entry from history tab by long pressing the item and make sure it gets deleted and app does not crash

**Comment by janagombitova** [comment]
App not crashing anymore and deletion happens as expected
