### ISSUE TITLE
Error saving  signature image on some devices

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#940]
https://sentry.io/akvo-foundation/flow-android/issues/404892596/

```
Exception: Error saving bitmap
    at org.akvo.flow.data.datasource.ImageDataSource.saveImage(ImageDataSource.java:68)
    at org.akvo.flow.data.datasource.ImageDataSource.saveImages(ImageDataSource.java:83)
    at org.akvo.flow.data.repository.FileDataRepository.saveImage(FileDataRepository.java:45)
    at org.akvo.flow.domain.interactor.SaveImage.buildUseCaseObservable(SaveImage.java:60)
    at org.akvo.flow.domain.interactor.UseCase.execute(UseCase.java:61)
...
(15 additional frame(s) were not displayed)

Throwable: Error saving image
java.lang.Exception: Error saving bitmap
	at org.akvo.flow.data.datasource.ImageDataSource.saveImage(ImageDataSource.java:68)
	at org.akvo.flow.data.datasource.ImageDataSource.saveImages(ImageDataSource.java:83)
	at org.akvo.flow.data.repository.FileDataRepository.saveImage(FileDataRepository.java:45)
	at org.akvo.flow.domain.interactor.SaveImage.buildUseCaseObservable(SaveImage.java:60)
	at org.akvo.flow.domain.interactor.UseCase.execute(UseCase.java:61)
	at org.akvo.flow.presentation.signature.SignaturePresenter.onSaveButtonTap(SignaturePresenter.java:108)
	at org.akvo.flow.presentation.signature.SignatureActivity.onSaveButtonTap(SignatureActivity.java:160)
	at org.akvo.flow.presentation.signature.SignatureActivity_ViewBinding$2.doClick(SignatureActivity_ViewBinding.java:69)
	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
	at android.view.View.performClick(View.java:4463)
	at android.view.View$PerformClick.run(View.java:18770)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

    at org.akvo.flow.util.logging.SentryTree.captureException(SentryTree.java:64)
    at org.akvo.flow.util.logging.SentryTree.log(SentryTree.java:56)
    at timber.log.Timber$Tree.prepareLog(Timber.java:545)
    at timber.log.Timber$Tree.e(Timber.java:469)
    at timber.log.Timber$1.e(Timber.java:321)
...
(15 additional frame(s) were not displayed)

Error saving image
java.lang.Exception: Error saving bitmap
	at org.akvo.flow.data.datasource.ImageDataSource.saveImage(ImageDataSource.java:68)
	at org.akvo.flow.data.datasource.ImageDataSource.saveImages(ImageDataSource.java:83)
	at org.akvo.flow.data.repository.FileDataRepository.saveImage(FileDataRepository.java:45)
	at org.akvo.flow.domain.interactor.SaveImage.buildUseCaseObservable(SaveImage.java:60)
	at org.akvo.flow.domain.interactor.UseCase.execute(UseCase.java:61)
	at org.akvo.flow.presentation.signature.SignaturePresenter.onSaveButtonTap(SignaturePresenter.java:108)
	at org.akvo.flow.presentation.signature.SignatureActivity.onSaveButtonTap(SignatureActivity.java:160)
	at org.akvo.flow.presentation.signature.SignatureActivity_ViewBinding$2.doClick(SignatureActivity_ViewBinding.java:69)
	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
	at android.view.View.performClick(View.java:4463)
	at android.view.View$PerformClick.run(View.j...
```

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/406131923/

**Comment by valllllll2000** [comment]
## Test plan
Create a survey with a signature question. Try answering to the signature question on the device. Check that signature question is properly saved and there are not failures.

**Comment by valllllll2000** [comment]
Closing as the issue has been fixed
