### ISSUE TITLE
Crash in caddisflyResult

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#955]
https://sentry.io/akvo-foundation/flow-android/issues/413012097/

```
IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 3 path $
    at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
    at com.google.gson.Gson.fromJson(Gson.java:888)
    at com.google.gson.Gson.fromJson(Gson.java:853)
    at com.google.gson.Gson.fromJson(Gson.java:802)
...
(17 additional frame(s) were not displayed)

JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 3 path $
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
    at com.google.gson.Gson.fromJson(Gson.java:888)
    at com.google.gson.Gson.fromJson(Gson.java:853)
    at com.google.gson.Gson.fromJson(Gson.java:802)
    at com.google.gson.Gson.fromJson(Gson.java:774)
...
(16 additional frame(s) were not displayed)

RuntimeException: Failure delivering result ResultInfo{who=null, request=5, result=-1, data=Intent { act=org.akvo.flow.action.caddisfly typ=text/plain flg=0x3000000 cmp=org.akvo.caddisfly/.ui.ExternalActionActivity (has extras) }} to activity {org.akvo.flow/org.akvo.flow.activity.FormActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 3 path $
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3717)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3760)
    at android.app.ActivityThread.access$1400(ActivityThread.java:153)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
    at android.os.Handler.dispatchMessage(Handler.java:102)
...
(5 additional frame(s) were not displayed)

Failure delivering result ResultInfo{who=null, request=5, result=-1, data=Intent { act=org.akvo.flow.action.caddisfly typ=text/plain flg=0x3000000 cmp=org.akvo.caddisfly/.ui.ExternalActionActivity (has extras) }} to activity {org.akvo.flow/org.akvo.flow.activity.FormActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 3 path $
```
Caddislfy results should not crash the app, we need to add a way to check the result is correct and if not then sow an error message to the user

**Comment by valllllll2000** [comment]
This no longer happens
