### ISSUE TITLE
App crashes while responding an Image question

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#999]
Crash report:

https://sentry.io/akvo-foundation/flow-android/issues/379788838/

```
OutOfMemoryError: Failed to allocate a 9734412 byte allocation with 2698528 free bytes and 2MB until OOM
    at org.akvo.flow.util.ImageUtil.resizeImage(ImageUtil.java:89)
    at org.akvo.flow.util.MediaFileHelper.getImageFilePath(MediaFileHelper.java:67)
    at org.akvo.flow.activity.FormActivity.onActivityResult(FormActivity.java:547)
...
(14 additional frame(s) were not displayed)

Failed to allocate a 9734412 byte allocation with 2698528 free bytes and 2MB until OOM
```

## Steps to reproduce:
Happens mostly on Motorola G3 device but to a lesser extend to some samsung devices: for example galaxy grand, galaxy s3 mini, Galaxy J1 Ace, galaxy core, galaxy tab E.
Create a survey with one or more image questions
In the app settings select the highest image size: 1280x960px
Keep on filing the forms until the app crashes

**Comment by valllllll2000** [comment]
After some more digging here are the changes that would reduce the occurencies of crashes due to OOME:
1) Replace LinearLayouts inside ScrollView by recyclerview.
2) Split MediaQuestionView into Video and Image in order to improve the image processing (having them in one view starts to be too complex and they are quite diferent so should be split.
